language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_install:
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - composer update
  - vendor/bin/phpunit --bootstrap bootstrap.php --configuration phpunit.xml
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: false
